/************\
*  Given two strings s and t which consist of only lowercase letters.
*  String t is generated by random shuffling string s and then add one more letter at a random position.
*  Find the letter that was added in t.
\************/

#include <string.h>

char findTheDifference(char* s, char* t) {
    int a[26] = {0 * 26};
    int b[26] = {0 * 26};
    
    int i = 0;
    
    int l = strlen(t);
    
    for (i = 0; i < l - 1; i++){
        a[s[i] - 'a']++;
        b[t[i] - 'a']++;
    }
    b[t[i] - 'a']++;
    for (i = 0; i < 26; i++) {
        if (a[i] != b[i])
            break;
    }
    return 'a' + i;
    
}
